version: '3.8'
services:
  app:
    build: 
      context: .. 
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EXTERNAL_API_URL=https://dummyjson.com
      - CACHE_TTL=300
      - DATABASE_URL=sqlite+aiosqlite:///./tickethub.db
    volumes:
      - ../src:/app/src
      - ../tickethub.db:/app/tickethub.db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
