version: '3.8'
services:
  app:
    build: 
      context: .. 
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - DATABASE_URL= ${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CACHE_TTL=${CACHE_TTL}
      - LOG_LEVEL=${LOG_LEVEL}
      - RATE_LIMIT=${RATE_LIMIT}
      - CACHING_ENABLED=${CACHING_ENABLED}
    volumes:
      - ../src:/app/src
      - ../tickethub.db:/app/tickethub.db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
